pinkie_pie
dkotegov/selenium-homework pull request #12
Opened 2016-12-28 17:43 UTC by Ustimov

Команда:
Устимов Артем
Шишкин Артём
Белянова Марина
Галаганов Максим

Чек лист:
1. Переход к фото
2. Создание альбома
3. Открытие альбома
4. Открытие фото
5. Закрытие фото
6. Поворот фото
7. Удаление фото
8. Восстановление фото
9. Переход к следующему фото
10. Удаление альбома

2016-12-30 11:20 UTC, dkotegov commented
Тесты падают:
 ```
msk-wire-macbook-pro-d:selenium-homework (master) Dmitry$ python run_tests.py
Seismograph is measuring:

......F.F

Seismograph is reporting about reasons:

==========================================================================================
<tests.test_photo:TestDeleteRestorePhoto method_name=test stopped_on=delete_restore_photo>
==========================================================================================
History (was done earlier):
  1. Login to ok.ru
  2. Test delete and restore photo

Current step (when exception was raised):
  <TestDeleteRestorePhoto.delete_restore_photo(2): Test delete and restore photo>

Current flow (context of steps execution):
  Without flows

Selenium (info from selenium extension):
  browser name: chrome
  last css query: a[class="lp ml-2x"]

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 227, in run_test
    _run_step(self, step_method)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 142, in _run_step
    method(case)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/case.py", line 42, in wrapper
    self, selenium.browser, *args, **kwargs
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 44, in wrapped
    return _call_to_method(self, method, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 154, in _call_to_method
    return method(case, *args, **kwargs) if case else method(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/test_photo.py", line 96, in delete_restore_photo
    self.assertion.true(photo_page.delete_restore_photo())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 287, in true
    self.__unittest__.assertTrue(expr, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

=======================================================================
<tests.test_photo:TestNextPhoto method_name=test stopped_on=next_photo>
=======================================================================
History (was done earlier):
  1. Login to ok.ru
  2. Text next photo

Current step (when exception was raised):
  <TestNextPhoto.next_photo(2): Text next photo>

Current flow (context of steps execution):
  Without flows

Selenium (info from selenium extension):
  browser name: chrome
  last css query: img[id="__plpcte_target"]

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 227, in run_test
    _run_step(self, step_method)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 142, in _run_step
    method(case)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/case.py", line 42, in wrapper
    self, selenium.browser, *args, **kwargs
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 44, in wrapped
    return _call_to_method(self, method, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 154, in _call_to_method
    return method(case, *args, **kwargs) if case else method(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/test_photo.py", line 117, in next_photo
    self.assertion.true(photo_page.next_photo())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 287, in true
    self.__unittest__.assertTrue(expr, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

----------------------------------------------------------------
tests=9 failures=2 errors=0 skipped=0 successes=7 runtime=54.695
```

2016-12-30 11:24 UTC, dkotegov commented on pages/photo_page.py
> +        return prev_size != self.photo.size
Эти проверки должны быть в тестах

2016-12-30 11:26 UTC, dkotegov commented
Проверки перенесите в тесты
А копипасту в setUp и tearDown

2016-12-30 11:26 UTC, dkotegov requested changes

2016-12-30 11:26 UTC, dkotegov commented on tests/test_photo.py
> +        photo_page = PhotoPage(browser)
Копипаст, вынесите в setUp

2017-01-04 19:24 UTC, Ustimov commented
Копипасту вынес в отдельные шаги, проверки вынес в тесты. Большую часть времени тесты проходят, но бывает, что падают.

2017-01-12 15:16 UTC, dkotegov commented
Принято

2017-01-12 15:16 UTC, closed without merging