no_python_team
dkotegov/selenium-homework pull request #4
Opened 2016-12-12 12:55 UTC by Antonboom

#### Команда no_python:

- Антон Телышев
- Дмитрий Мовчан
- Евгений Козинченко
- Алексей Мокеев

#### Чек-лист:
- Создать заметку с помощью нескольких текстовых полей
- Создать заметку с прикрепленными фотографиями
- Создать заметку с прикрепленной музыкой (+ поиск музыки)
- Создать заметку с прикрепленной картой
- Создать заметку и отметить пользователя
- Проверить удаление заметок и их восстановление
- Проверить возможность редактирования заметок
- Проверить возможность комментирования заметки
- Поставить "класс" заметке несколькими вариантами
- Поставить заметку в статус

2016-12-17 11:05 UTC, dkotegov requested changes

2016-12-17 11:05 UTC, dkotegov commented on elements/pages.py
> +            time.sleep(1)
Слипов быть не должно

2016-12-17 11:05 UTC, dkotegov commented on tests/notes/test_comment.py
> +def test_comment(case, browser):
Тест не атомарный, если первая проверка упадет, остальные не выполнятся

2016-12-17 11:05 UTC, dkotegov commented on tests/notes/test_comment.py
> +    time.sleep(1)
;(

2016-12-17 11:05 UTC, dkotegov commented on tests/notes/test_comment.py
> +    last_note.delete()
Если ассерт выше упадет, эта строчка не выполнится

2016-12-17 11:07 UTC, dkotegov commented
Нужно сделать тесты атомартыми, разбить на suite, в них сделать setup и teardown, и внутри suite разбить проверки на отдельные тесты
И убрать все слипы

2017-04-21 18:38 UTC, Antonboom commented
Не закрывай реквест, пожалуйста
Эта штука не дает мне спать, хочу доделать

2017-04-21 19:10 UTC, dkotegov commented
O_O

2020-03-27 21:29 UTC, Antonboom commented
😢

2020-03-27 21:29 UTC, closed without merging

2020-03-28 19:12 UTC, dkotegov commented
;(