Команда undefined
dkotegov/selenium-homework pull request #5
Opened 2016-12-12 13:22 UTC by Vertaler

Не проходит все тесты, так как на ОК есть баг, из-за которого невозможно открыть видео в новой вкладке.

2016-12-17 11:50 UTC, dkotegov requested changes

2016-12-17 11:50 UTC, dkotegov commented on pages/channel_page.py
> +                       '*/descendant::i[contains(@class,"tag_del")]'
Этот селектор будет не стабильным

2016-12-17 11:50 UTC, dkotegov commented on pages/channel_page.py
> +        self.browser.execute_script('arguments[0].click();', delete_elem._wrapped)
А почему через JS?

2016-12-17 11:50 UTC, dkotegov commented on pages/channel_page.py
> +        if title is not None:
Просто `if title`

2016-12-17 11:50 UTC, dkotegov commented on pages/video_page.py
> +        # ActionChains(self.browser).move_to_element(progress_bar).move_by_offset((progress_bar_width/100)*(percent-50), 0).click().perform()
Зачем здесь это?

2016-12-17 11:50 UTC, dkotegov commented on tests/channels_test.py
> +    def test_add_tags(self):#TODO исправить
Исправьте, раз TODO ;)

2016-12-17 11:50 UTC, dkotegov commented on tests/comments_test.py
> +        last_comment.remove()
Если ассерт сверху упадет, то коммент не удалится

2016-12-17 11:50 UTC, dkotegov commented on utils.py
> +            time.sleep(DEFAULT_SLEEP_TIME)
Ну нет же! :)

2016-12-17 11:50 UTC, dkotegov commented on utils.py
> +def wait(driver, condition, timeout=DEFAULT_TIMEOUT, sleeptime=DEFAULT_SLEEP_TIME):
Уже есть в seismograph

2016-12-17 13:00 UTC, Vertaler commented on pages/channel_page.py
> +        self.browser.execute_script('arguments[0].click();', delete_elem._wrapped)
Через обычный клик ElementNotVisibleException бросается

2016-12-17 13:03 UTC, Vertaler commented on pages/channel_page.py
> +                       '*/descendant::i[contains(@class,"tag_del")]'
Не нашёл более простого способа выбрать тег по тексту.

2016-12-17 13:06 UTC, Vertaler commented on pages/video_page.py
> +        # ActionChains(self.browser).move_to_element(progress_bar).move_by_offset((progress_bar_width/100)*(percent-50), 0).click().perform()
Ранее использовались ActionChains для клика по определённому смещению элемента. Но они не работали в Firefox. Закоменченный код уберу.

2016-12-17 13:11 UTC, Vertaler commented on utils.py
> +            time.sleep(DEFAULT_SLEEP_TIME)
А как правильно бороться с StaleElementReferenceException?

2016-12-17 15:23 UTC, Vertaler commented on tests/comments_test.py
> +        last_comment.remove()
Вынес в teardown

2016-12-17 15:23 UTC, Vertaler commented on pages/channel_page.py
> +        if title is not None:
Исправил

2016-12-17 15:23 UTC, Vertaler commented on pages/video_page.py
> +        # ActionChains(self.browser).move_to_element(progress_bar).move_by_offset((progress_bar_width/100)*(percent-50), 0).click().perform()
Убрал.

2016-12-17 15:24 UTC, Vertaler commented on tests/channels_test.py
> +    def test_add_tags(self):#TODO исправить
Исправил

2016-12-17 15:25 UTC, Vertaler commented on utils.py
> +            time.sleep(DEFAULT_SLEEP_TIME)
Переделал через wait.

2016-12-17 17:54 UTC, Vertaler commented on utils.py
> +def wait(driver, condition, timeout=DEFAULT_TIMEOUT, sleeptime=DEFAULT_SLEEP_TIME):
Теперь используется waiting_for из сейсмографа

2016-12-18 13:05 UTC, dkotegov commented
Тесты падают и виснут в середине прогона:
```msk-wire-macbook-pro-d:selenium-homework (master) Dmitry$ python run_tests.py
Seismograph is measuring:

.......E.......F...........EE^C

Seismograph is reporting about reasons:

==============================================================================================
<tests.channels_test:ChangeChannelCase method_name=test_move_video stopped_on=test_move_video>
==============================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/channels_test.py", line 78, in test_move_video
    source.move_video(VIDEO_NAME, DESTINATION_NAME)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/channel_page.py", line 178, in move_video
    self.click_edit_video(name)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 23, in wrapper
    lambda: not raises_stale_element_reference_exception(func, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/proxy.py", line 259, in waiting_for
    message=message,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/utils/common.py", line 21, in waiting_for
    result = func(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 23, in <lambda>
    lambda: not raises_stale_element_reference_exception(func, *args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 14, in raises_stale_element_reference_exception
    func(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/channel_page.py", line 161, in click_edit_video
    edit_button = utils.wait_xpath(self.browser, self.EDIT_VIDEO_XPATH_TEMPLATE.format(name))
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 30, in wait_xpath
    return driver.waiting_for(lambda : driver.find_element_by_xpath(xpath), timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/proxy.py", line 259, in waiting_for
    message=message,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/utils/common.py", line 21, in waiting_for
    result = func(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 30, in <lambda>
    return driver.waiting_for(lambda : driver.find_element_by_xpath(xpath), timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/interfaces/webdriver.py", line 105, in find_element_by_xpath
    return self.__getattr_from_webdriver_or_webelement__('find_element_by_xpath')(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/polling.py", line 49, in wrapped
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/proxy.py", line 29, in wrapper
    result = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //div[@class="vid-card js-sortable"]/child::a[@title="VIDEO_TO_MOVE"]/following-sibling::div[@class="vid-card_ac"]/descendant::a[contains(@class,"vl_ic_edit")]
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'msk-wire-macbook-pro-d.kotegov.mail.msk', ip: '100.96.167.230', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.2', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAEJ9kkkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJU0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3URU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90gHysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/XpELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQM6zAyIvdF4ixSbjadQhq87UXtRpTwwx+uBN3NjtyE9u4mIjc1WDVn+Ii4+I4xBhJwU04p6JEKH6nMxvfr0an02th/SKMQZyAfbE9Iy7Djzy83e5PTdXN9NTpSg2Gl1FrlErekg9nrH9KOu24F+6Ot+TTm5nQ0zi3ZqJRBGXdGk/zMkqQHHJa+Br7/1gvW1//L6cUaYEDJFzGYmweTS/L/LsjJVlV4OW1xW+/d6qcv4GrUR27WQKrFPy6oO6sS023Mdb/wfaaNjI5AG98KOiIu0Szo4wGi3yqTVE4mNC+TMLrPre1X6aPsVYLdl/ANQSwcIy87bUaYDAAC2DAAAUEsBAhQAFAAICAgAQn2SScvO21GmAwAAtgwAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA2wMAAAAA}, appBuildId=20161104212021, version=, platform=MAC, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=85642, browserVersion=50.0, platformVersion=16.3.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, takesElementScreenshot=true, platformName=darwin}]
Session ID: 2e63129d-59f2-1840-816f-0f4347b1075a
*** Element info: {Using=xpath, value=//div[@class="vid-card js-sortable"]/child::a[@title="VIDEO_TO_MOVE"]/following-sibling::div[@class="vid-card_ac"]/descendant::a[contains(@class,"vl_ic_edit")]}
Screenshot: available via screen
Stacktrace:
    at sun.reflect.GeneratedConstructorAccessor18.newInstance (None:-1)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:422)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException (W3CHttpResponseCodec.java:127)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:93)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:42)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute (HttpCommandExecutor.java:163)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute (DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:601)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement (RemoteWebDriver.java:368)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath (RemoteWebDriver.java:473)
    at [...]

2016-12-18 14:02 UTC, Vertaler commented
`WebDriverException: Message: File not found: /Users/Dmitry/TPHomeWork/stud/unnamed.png`

Странно, что не находится этот файл, в репозитории он есть и у меня нормально работает.

2016-12-18 15:11 UTC, dkotegov commented
Я запускаю тесты через `python run_tests.py`, картинка лежит рядом, а в тестах `../unnamed.png`

2016-12-18 19:52 UTC, Vertaler commented
Заменил путь к картинке на "./unnamed.png".
Исправил другие ошибки.

2016-12-18 22:48 UTC, dkotegov commented
Перестал подходить пароль

2016-12-18 22:56 UTC, dkotegov commented
Теперь не зависает, но продолжает падать:
```
MacBook-Pro:selenium-homework (master) Dmitry$ python run_tests.py
Seismograph is measuring:

.......F.......F..............

Seismograph is reporting about reasons:

==============================================================================================
<tests.channels_test:ChangeChannelCase method_name=test_move_video stopped_on=test_move_video>
==============================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/channels_test.py", line 80, in test_move_video
    self.assertion.is_in(VIDEO_NAME, destination.get_videos_titles())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 347, in is_in
    self.__unittest__.assertIn(member, container, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 803, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: 'VIDEO_TO_MOVE' not found in [u'\u0424\u043e\u0440\u0441\u0430\u0436 8 \u2014 \u0420\u0443\u0441\u0441\u043a\u0438\u0439 \u0442\u0440\u0435\u0439\u043b\u0435\u0440 (2016)']

=========================================================================================================
<tests.videopreview_test:VideoPreviewCase method_name=test_open_in_newtab stopped_on=test_open_in_newtab>
=========================================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/videopreview_test.py", line 40, in test_open_in_newtab
    self.assertion.equal(url_related_video, self.browser.current_url)  # bug in ok.ru here
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 305, in equal
    self.__unittest__.assertEqual(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 924, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: u'https://www.ok.ru/video/218562890379' != u'https://www.ok.ru/feed?st.cmd=userMain'
- https://www.ok.ru/video/218562890379
+ https://www.ok.ru/feed?st.cmd=userMain


-------------------------------------------------------------------
tests=30 failures=2 errors=0 skipped=0 successes=28 runtime=363.556
```

2016-12-19 09:27 UTC, Vertaler commented
Проверка открытия видео в новой вкладке фейлится из-за бага в ОК:
http://st-jira.tech-mail.ru/browse/TECH-487

А тест на перемещение видео действительно неправильно работал в Firefox - сейчас должно быть всё нормально.

2016-12-19 21:05 UTC, dkotegov commented
Продолжает падать:
```
msk-wire-macbook-pro-d:selenium-homework (master) Dmitry$ python run_tests.py
Seismograph is measuring:

F...F..........F.............E

Seismograph is reporting about reasons:

=======================================================================================================
<tests.comments_test:AddCommentCase method_name=test_video_attachment stopped_on=test_video_attachment>
=======================================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/comments_test.py", line 85, in test_video_attachment
    self.video_page.add_comment(video=True)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/video_page.py", line 302, in add_comment
    self.send_comment_form.add_comment(text, video, photo, photo_pc)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/video_page.py", line 71, in add_comment
    self.attach_video()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/video_page.py", line 94, in attach_video
    self.video_dialog.click_first()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 19, in wrapper
    lambda: raises_stale_element_reference_exception(func, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/proxy.py", line 259, in waiting_for
    message=message,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/utils/common.py", line 30, in waiting_for
    raise exc_cls(message)
PollingTimeoutExceeded: Wait timeout "30" has been exceeded
======================================================================================
<tests.channels_test:CreateChannelCase method_name=test_create stopped_on=test_create>
======================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/channels_test.py", line 27, in test_create
    self.assertion.is_not_in(self.TEST_CHANNEL1, self.browser.page_source)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 353, in is_not_in
    self.__unittest__.assertNotIn(member, container, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 810, in assertNotIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: 'TEST_CHANNEL1' unexpectedly found in <.......>

==========================================================================================
<tests.channels_test:ChangeChannelCase method_name=test_add_tags stopped_on=test_add_tags>
==========================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/channels_test.py", line 105, in test_add_tags
    self.assertion.is_not_in(NEW_TAG, channel_page.get_video_tags(VIDEO_NAME))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 353, in is_not_in
    self.__unittest__.assertNotIn(member, container, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 810, in assertNotIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: 'TAGTAGTAG' unexpectedly found in [u'', u'test', u'tess', u'OLOO', u'T', u'TAGTAGTAG']

=========================================================================================================
<tests.videopreview_test:VideoPreviewCase method_name=test_open_in_newtab stopped_on=test_open_in_newtab>
=========================================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/videopreview_test.py", line 40, in test_open_in_newtab
    self.assertion.equal(url_related_video, self.browser.current_url)  # bug in ok.ru here
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 305, in equal
    self.__unittest__.assertEqual(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 924, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: u'https://www.ok.ru/video/196028402412' != u'https://www.ok.ru/feed?st.cmd=userMain'
- https://www.ok.ru/video/196028402412
+ https://www.ok.ru/feed?st.cmd=userMain


-------------------------------------------------------------------
tests=30 failures=3 errors=1 skipped=0 successes=26 runtime=404.637
```

2016-12-19 21:07 UTC, dkotegov commented
> Проверка открытия видео в новой вкладке фейлится из-за бага в ОК

Зарепортите баг в ОК и скипните тест, не нужно оставлять падающий

2016-12-20 21:44 UTC, dkotegov commented
Можно проверять?

2016-12-20 22:02 UTC, nickshch commented
Дайте нам, пожалуйста, еще 10 минут на контрольный запуск тестов и можно проверять. Спасибо.

2016-12-20 22:05 UTC, dkotegov commented
Ага, жду)
Не торопитесь, лучше убедитесь, что все работает)

2016-12-20 22:44 UTC, dkotegov commented on tests/channels_test.py
> -        self.assertion.equal(self.channel_page.videos_count, self.DEFAULT_VIDEOS_COUNT + 1)
Нет ассерта - нет проблемы)

2016-12-20 22:46 UTC, dkotegov commented on tests/channels_test.py
> +        self.assertion.equal(self.page.subscriptions_count, self.DEFAULT_SUBSCRIPTIONS_COUNT)
Если любой из этих ассертов упадет, браузер не закроется

2016-12-20 23:15 UTC, Vertaler commented
Мы готовы к проверке.

2016-12-21 00:16 UTC, dkotegov commented
И продолжает падать:
```
MacBook-Pro:selenium-homework (master) Dmitry$ python run_tests.py
Seismograph is measuring:

.E....EE...FE.ES..............

Seismograph is reporting about reasons:

====================================================================================================================
<tests.channels_test:CreateChannelCase method_name=test_create_from_left_menu stopped_on=test_create_from_left_menu>
====================================================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/channels_test.py", line 29, in test_create_from_left_menu
    self.video_page.create_channel_left_menu(self.TEST_CHANNEL2)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/myvideos_page.py", line 31, in create_channel_left_menu
    self.create_channel_dialog.create_channel(name)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/myvideos_page.py", line 19, in create_channel
    utils.wait_change_url(self.browser)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 51, in wait_change_url
    return driver.waiting_for(lambda: driver.current_url != current_url, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/proxy.py", line 259, in waiting_for
    message=message,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/utils/common.py", line 30, in waiting_for
    raise exc_cls(message)
PollingTimeoutExceeded: Wait timeout "30" has been exceeded

============================================================================================================
<tests.channels_test:ChangeChannelCase method_name=test_change_video_name stopped_on=test_change_video_name>
============================================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/channels_test.py", line 112, in test_change_video_name
    channel_page.edit_video(OLD_VIDEO_NAME, title=NEW_VIDEO_NAME)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/channel_page.py", line 162, in edit_video
    self.click_edit_video(name)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 19, in wrapper
    lambda: raises_stale_element_reference_exception(func, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/proxy.py", line 259, in waiting_for
    message=message,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/utils/common.py", line 21, in waiting_for
    result = func(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 19, in <lambda>
    lambda: raises_stale_element_reference_exception(func, *args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 10, in raises_stale_element_reference_exception
    func(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/channel_page.py", line 158, in click_edit_video
    edit_button = utils.wait_xpath(self.browser, self.EDIT_VIDEO_XPATH_TEMPLATE.format(name))
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 26, in wait_xpath
    return driver.waiting_for(lambda : driver.find_element_by_xpath(xpath), timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/proxy.py", line 259, in waiting_for
    message=message,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/utils/common.py", line 21, in waiting_for
    result = func(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/utils.py", line 26, in <lambda>
    return driver.waiting_for(lambda : driver.find_element_by_xpath(xpath), timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/interfaces/webdriver.py", line 105, in find_element_by_xpath
    return self.__getattr_from_webdriver_or_webelement__('find_element_by_xpath')(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/polling.py", line 49, in wrapped
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/proxy.py", line 29, in wrapper
    result = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: //div[@class="vid-card js-sortable"]/child::a[@title="OLD_VIDEO_NAME"]/following-sibling::div[@class="vid-card_ac"]/descendant::a[contains(@class,"vl_ic_edit")]
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'pf1.i', ip: '10.0.0.6', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.2', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAJMYlUkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJU0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3URU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90gHysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/XpELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQM6zAyIvdF4ixSbjadQhq87UXtRpTwwx+uBN3NjtyE9u4mIjc1WDVn+Ii4+I4xBhJwU04p6JEKH6nMxvfr0an02th/SKMQZyAfbE9Iy7Djzy83e5PTdXN9NTpSg2Gl1FrlErekg9nrH9KOu24F+6Ot+TTm5nQ0zi3ZqJRBGXdGk/zMkqQHHJa+Br7/1gvW1//L6cUaYEDJFzGYmweTS/L/LsjJVlV4OW1xW+/d6qcv4GrUR27WQKrFPy6oO6sS023Mdb/wfaaNjI5AG98KOiIu0Szo4wGi3yqTVE4mNC+TMLrPre1X6aPsVYLdl/ANQSwcIy87bUaYDAAC2DAAAUEsBAhQAFAAICAgAkxiVScvO21GmAwAAtgwAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA2wMAAAAA}, appBuildId=20161104212021, version=, platform=MAC, proxy={}, command_id [...]

2016-12-21 14:35 UTC, dkotegov commented
Принято

2016-12-21 14:35 UTC, closed without merging