Команда "Дудцы"
dkotegov/selenium-homework pull request #6
Opened 2016-12-12 18:56 UTC by sp41mer

Наши чек-листы здесь:
http://st-jira.tech-mail.ru/browse/TECH-654

2016-12-17 12:14 UTC, dkotegov requested changes

2016-12-17 12:14 UTC, dkotegov commented on pages/feed_page.py
> +        time.sleep(2)
Слипов в тестах быть не должно

2016-12-17 12:14 UTC, dkotegov commented on pages/feed_page.py
> +        return 1
Нигде не используется

2016-12-17 12:14 UTC, dkotegov commented on pages/feed_page.py
> +        return 1
Зачем `return 1`?
Тоже нигде не используется

2016-12-17 12:14 UTC, dkotegov commented on pages/feed_page.py
> +            assert False
Этот if надо заменять на один assert

2016-12-17 12:14 UTC, dkotegov commented on pages/feed_page.py
> +            assert False
И тут

2016-12-17 12:14 UTC, dkotegov commented on smth/Auth.py
> +    AUTH_PASSWORD = 'Gfhjkmlkzjr1488'
Не храните пароли в гите

2016-12-17 12:14 UTC, dkotegov commented on smth/xpath.py
> +    def exist(self):
Уже есть в seismograph

2016-12-17 12:14 UTC, dkotegov commented on smth/xpath.py
> +#Stolen from https://github.com/nksoff/selenium-homework/blob/nikita/utils/xpath_query.py
?!

2016-12-17 12:14 UTC, dkotegov commented on tests/lenta_tests.py
> +    return url in browser.current_url
Используйте ассерты

2016-12-17 12:14 UTC, dkotegov commented
Все слипы надо убрать

2016-12-18 12:26 UTC, sp41mer commented on smth/xpath.py
> +#Stolen from https://github.com/nksoff/selenium-homework/blob/nikita/utils/xpath_query.py
Это я чтоб не было вопросов откуда эта либа и кто первоисточник указал

2016-12-18 12:33 UTC, shramru commented
так без слипов не работает ничего, как делать годные задержки?
а более того я запустил на ubuntu все эти тесты и бразуер тупо падает (ребята писали под макось), эта штука что ли не кроссплатформенная?
на разных платформах разные результаты, как пофиксить?)

2016-12-18 12:35 UTC, sp41mer commented
Если не ставить слипы, то в некоторых местах клик просто не делается, хотя элемент уже загружен.

2016-12-18 12:38 UTC, shramru commented
реально бомбит с фреймворка)
мы сидели несколько суток, пытаясь добиться нормального поведения, а там уже дедлайн и на хороший код времени не было уже.

2016-12-18 15:00 UTC, dkotegov commented
> так без слипов не работает ничего, как делать годные задержки?
> а более того я запустил на ubuntu все эти тесты и бразуер тупо падает (ребята писали под макось), эта штука что ли не кроссплатформенная?
> на разных платформах разные результаты, как пофиксить?)

Скачать бинарь geckodriver под свою платформу
Код кроссплатформенный, а драйверы нет

> Если не ставить слипы, то в некоторых местах клик просто не делается, хотя элемент уже загружен.

Нужно помнить, что селениум выполняет все действия моментально. Если есть два клика, первый открывает форму, второй что-то кликает или вводит на ней, селениум выполнит их практически одновременно. Если слип помогает тесту пройти, меняйте его на wait, который ждет элемента с которым будет производится следующее действие

> реально бомбит с фреймворка)
мы сидели несколько суток, пытаясь добиться нормального поведения, а там уже дедлайн и на хороший код времени не было уже.

Чем бы вы не занимались, всегда будут какие-то сроки и всегда будет не хватать времени.
Нужно уметь сразу делать хорошо, расставлять приоритеты и учитывать возможные риски.
Так что в курсе по обеспечению качества надо писать качественный код) Делайте)

2016-12-18 15:06 UTC, dkotegov commented on smth/xpath.py
> +#Stolen from https://github.com/nksoff/selenium-homework/blob/nikita/utils/xpath_query.py
Вопросы все равно есть. Зачем вам кусок кода из чужой работы? 
Вместе со всеми ошибками.

2016-12-18 15:17 UTC, sp41mer commented on smth/xpath.py
> +#Stolen from https://github.com/nksoff/selenium-homework/blob/nikita/utils/xpath_query.py
Я думал, что это поможет проще работать с xpath. Но в итоге этой либой мы вроде нигде и не воспользовались. Поэтому если для Вас принципиально отсутствие этого файла, то мы можем его удалить и стереть из своей памяти любые воспоминания о нем)

2016-12-18 15:20 UTC, sp41mer commented
> Если слип помогает тесту пройти, меняйте его на wait, который ждет элемента с которым будет производится следующее действие

Как понять какой элемент нужно дожидаться? Если мы дожидаемся тот, по которому собираемся кликнуть, то клик все равно проскакивает :(

2016-12-18 15:44 UTC, shramru commented
> Скачать бинарь geckodriver под свою платформу
Код кроссплатформенный, а драйверы нет 

ну это все понятно, тесты ведут себя по-разному все равно.
ну ладно, мы просто прогоним на макоси)

2016-12-18 18:42 UTC, dkotegov commented on smth/xpath.py
> +#Stolen from https://github.com/nksoff/selenium-homework/blob/nikita/utils/xpath_query.py
У меня глаз дергается, когда я вижу чужой код, в вашей работе, давайте уберем ;)

2016-12-18 18:46 UTC, dkotegov commented
> Как понять какой элемент нужно дожидаться? Если мы дожидаемся тот, по которому собираемся кликнуть, то клик все равно проскакивает :(
И еще очень часто появляется окно "ожидания" поверх того элемента, в итоге элемент уже загрузился, но селениум кликает в прелоадер и падает. Как проверять, что элемент сначала появился, а потом исчез?

Так и проверяйте, что прелоудер исчез, через not exist или not visible

2016-12-18 18:48 UTC, dkotegov commented
> ну это все понятно, тесты ведут себя по-разному все равно.
ну ладно, мы просто прогоним на макоси)

Стабильность напрямую зависит от ожиданий, потому что какие-то компьютеры быстрее, какие-то медленнее, поэтому как только добавляете слипы, всё начинает работать

2016-12-26 21:02 UTC, shramru commented
переписал тесты

2016-12-26 22:18 UTC, dkotegov requested changes

2016-12-26 22:18 UTC, dkotegov commented on pages/comment_page.py
> +            raise WebDriverException
Лучше добавлять текст о том, что именно произошло

2016-12-26 22:18 UTC, dkotegov commented on pages/feed_page.py
> +    @selenium.polling.wrap(delay=1)
А таймаут?

2016-12-26 22:18 UTC, dkotegov commented on pages/feed_page.py
> +        self.browser.execute_script('''$('.filter_i')[2].click()''')
Почему через JS?

2016-12-26 22:18 UTC, dkotegov commented on pages/feed_page.py
> +            raise WebDriverException
Похоже на костыль. Здесь поллинг не нужен, никаких действий не производится

2016-12-26 22:18 UTC, dkotegov commented on pages/feed_page.py
> +            raise WebDriverException
И тут

2016-12-26 22:18 UTC, dkotegov commented on pages/feed_page.py
> +        return self.browser.find_element_by_xpath('//*[@class="feed"]/div[3]/div[1]/span[1]/span/a').get_attribute('href')
Этот xpath будет очень не стабильным

2016-12-26 22:18 UTC, dkotegov commented on pages/feed_page.py
> +            return
Зачем? Пусть падает

2016-12-26 22:18 UTC, dkotegov commented on pages/feed_page.py
> +        assert comment_div.text == 'lel'
Этому место в тесте

2016-12-26 22:18 UTC, dkotegov commented on pages/feed_page.py
> +        assert len(like_div.text) == 2
И этому

2016-12-26 22:18 UTC, dkotegov commented on pages/feed_page.py
> +        assert len(like_div.text) != 2
И тут

2016-12-26 22:18 UTC, dkotegov commented on pages/profile_page.py
> +            raise WebDriverException
И тут

2016-12-26 22:18 UTC, dkotegov commented on pages/someone_post_page.py
> +            raise WebDriverException
И тут

2016-12-26 22:18 UTC, dkotegov commented on tests/lenta_tests.py
> +    browser.execute_script('''$('.feed_h').first().find('a').first().click()''')
Все взаимодействия с браузером должны быть в PageObject
А все проверки - в тестах

2016-12-26 22:18 UTC, dkotegov commented on tests/lenta_tests.py
> +    feed_page.make_like_on_own_post()
42

2016-12-26 22:18 UTC, dkotegov commented on tests/lenta_tests.py
> +    feed_page.make_self_comment()
do_smth(1)
do_smth(2)
А где ассерты? ;)

2016-12-26 22:18 UTC, dkotegov commented on tests/lenta_tests.py
> +    assert u'Опубликовано!' in val
Воспользуйтесь ассертами из seismograph

2016-12-26 22:18 UTC, dkotegov commented on tests/lenta_tests.py
> +    profile_page.delete_my_post()
Если ассерт упадет, то пост не удалится

2016-12-26 22:22 UTC, shramru commented on pages/feed_page.py
> +    @selenium.polling.wrap(delay=1)
везде дефолтный 30

2016-12-26 22:23 UTC, shramru commented on pages/feed_page.py
> +        self.browser.execute_script('''$('.filter_i')[2].click()''')
потому что клик не работает нормально. тут половина этого сайта не кликается, если бы все работало сразу, я так долго бы не сидел)

2016-12-26 22:23 UTC, shramru commented on pages/feed_page.py
> +            raise WebDriverException
он ждет пока не появилось новое сообщение в чатике

2016-12-26 22:24 UTC, shramru commented on pages/feed_page.py
> +            raise WebDriverException
ждет, пока не сработает клик на лайк

2016-12-26 22:25 UTC, dkotegov commented on pages/feed_page.py
> +            raise WebDriverException
Так используйте wait :)

2016-12-27 15:33 UTC, shramru commented
requesting accepted

2016-12-27 18:22 UTC, dkotegov commented on pages/feed_page.py
> +        return text
Делать это через polling неправильно

2016-12-27 18:22 UTC, dkotegov commented on pages/feed_page.py
> +            raise WebDriverException(msg='Timeout at waiting like was set to comment')
И это

2016-12-27 18:23 UTC, dkotegov commented on pages/feed_page.py
> +            raise WebDriverException(msg='Timeout at waiting like was unset to comment')
И это

2016-12-27 18:23 UTC, dkotegov commented on pages/feed_page.py
> +        except:
Плохо перехватывать всё

2016-12-27 18:23 UTC, dkotegov commented on pages/feed_page.py
> +        try:
Так оно и так упадет, если не дождется

2016-12-27 18:24 UTC, dkotegov commented on pages/feed_page.py
> +            raise WebDriverException(msg='Timeout at waiting url changed')
И это

2016-12-27 18:24 UTC, dkotegov commented on pages/group_post_page.py
> +            raise WebDriverException(msg='Timeout at waiting new message showed in modal')
И это

2016-12-27 18:24 UTC, dkotegov commented on pages/group_post_page.py
> +            raise WebDriverException(msg='Timeout at waiting comment modal')
И тут

2016-12-27 18:25 UTC, dkotegov commented on pages/post_page.py
> +            raise WebDriverException(msg='Timeout at waiting post was closed')
И тут

2016-12-27 18:26 UTC, dkotegov commented on pages/profile_page.py
> +        try:
Оно и так упадет, если не найдет

2016-12-27 18:26 UTC, dkotegov commented on pages/profile_page.py
> +        except:
И тут

2016-12-27 18:29 UTC, shramru commented on pages/feed_page.py
> +        return text
я так понял мне сюда)

2016-12-27 18:29 UTC, shramru commented on pages/feed_page.py
> +        return text
http://selenium-python.readthedocs.io/waits.html

2016-12-27 18:30 UTC, dkotegov commented on pages/feed_page.py
> +        return text
Да, либо waitfor из seismograph

2016-12-27 19:51 UTC, shramru commented on pages/feed_page.py
> +        try:
так мне не надо, чтобы падало. Надо, чтобы скрипт заново кликнул, если не выполнился до этого

2016-12-27 19:56 UTC, dkotegov commented on pages/feed_page.py
> +        try:
Если он упадет, там будет exception, который polling и так перехватит

2016-12-27 20:07 UTC, shramru commented on pages/feed_page.py
> +        try:
Нет. Здесь же вылетает PollingTimeoutExceeded из seismograph.ext.selenium.exceptions. А вот базовое исключение, которое ловит wrapper - WebDriverException из selenium.common.exceptions. Так что я уже добавил это исключение в аргументы обертки

2016-12-27 20:39 UTC, shramru commented on pages/profile_page.py
> +        try:
IndexError тут

2016-12-27 21:14 UTC, shramru commented on pages/feed_page.py
> +        return text
а вот этот поллинг нужен, он скриптом кликает

2016-12-27 21:54 UTC, shramru commented
поправил

2016-12-27 22:23 UTC, dkotegov commented
Тесты падают:
```
MacBook-Pro:selenium-homework (master) Dmitry$ python run_tests.py
Seismograph is measuring:

...E............E

Seismograph is reporting about reasons:

====================================================================
<tests.lenta_tests:TestGetPost method_name=test stopped_on=get_post>
====================================================================
History (was done earlier):
  1. Auth
  2. Test get post

Current step (when exception was raised):
  <TestGetPost.get_post(2): Test get post>

Current flow (context of steps execution):
  Without flows

Selenium (info from selenium extension):
  browser name: firefox
  last css query: a[class="filter_i __active iblock-cloud_show"]

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 227, in run_test
    _run_step(self, step_method)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 142, in _run_step
    method(case)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/case.py", line 42, in wrapper
    self, selenium.browser, *args, **kwargs
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 44, in wrapped
    return _call_to_method(self, method, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 154, in _call_to_method
    return method(case, *args, **kwargs) if case else method(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/lenta_tests.py", line 34, in get_post
    url = feed_page.get_post()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/feed_page.py", line 161, in get_post
    wait.until_not(c.in_url(url))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 96, in until_not
    raise TimeoutException(message)
TimeoutException: Message:


==========================================================================================
<tests.reshari_tests:TestRepostFeedAndDelete method_name=test stopped_on=make_feed_repost>
==========================================================================================
History (was done earlier):
  1. Auth
  2. Test make feed repost

Current step (when exception was raised):
  <TestRepostFeedAndDelete.make_feed_repost(2): Test make feed repost>

Current flow (context of steps execution):
  Without flows

Selenium (info from selenium extension):
  browser name: firefox
  last css query: div[class="sc-menu __reshare __noarrow sc-menu__top"]

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 227, in run_test
    _run_step(self, step_method)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 142, in _run_step
    method(case)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/case.py", line 42, in wrapper
    self, selenium.browser, *args, **kwargs
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 44, in wrapped
    return _call_to_method(self, method, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 154, in _call_to_method
    return method(case, *args, **kwargs) if case else method(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/reshari_tests.py", line 87, in make_feed_repost
    feed_page.open_menu_in_feed()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/polling.py", line 49, in wrapped
    return f(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/feed_page.py", line 78, in open_menu_in_feed
    self.active_menu.wait()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/query.py", line 254, in wait
    message='Could not wait web element by css "{}"'.format(self.__css),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/utils/common.py", line 30, in waiting_for
    raise exc_cls(message)
PollingTimeoutExceeded: Could not wait web element by css "div[class="sc-menu __reshare __noarrow sc-menu__top"]"

-------------------------------------------------------------------
tests=17 failures=0 errors=2 skipped=0 successes=15 runtime=215.503
```

2016-12-27 23:51 UTC, dkotegov commented
Все еще падают
```
MacBook-Pro:selenium-homework (master) Dmitry$ python run_tests.py
Seismograph is measuring:

......E...E......

Seismograph is reporting about reasons:

============================================================================
<tests.lenta_tests:TestMakeComment method_name=test stopped_on=make_comment>
============================================================================
History (was done earlier):
  1. Auth
  2. Test make comment

Current step (when exception was raised):
  <TestMakeComment.make_comment(2): Test make comment>

Current flow (context of steps execution):
  Without flows

Selenium (info from selenium extension):
  browser name: firefox
  last css query: div[id="ok-e-d_button"]

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 227, in run_test
    _run_step(self, step_method)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 142, in _run_step
    method(case)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/case.py", line 42, in wrapper
    self, selenium.browser, *args, **kwargs
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 44, in wrapped
    return _call_to_method(self, method, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/steps.py", line 154, in _call_to_method
    return method(case, *args, **kwargs) if case else method(*args, **kwargs)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/lenta_tests.py", line 65, in make_comment
    val = feed_page.make_comment(PUBLIC_COMMENT)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/pages/feed_page.py", line 126, in make_comment
    comment_div = comment.find_element_by_css_selector('div.d_comment_text')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/interfaces/webelement.py", line 151, in find_element_by_css_selector
    return self.__getattr_from_webdriver_or_webelement__('find_element_by_css_selector')(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/polling.py", line 49, in wrapped
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/ext/selenium/proxy/proxy.py", line 29, in wrapper
    result = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 307, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 511, in find_element
    {"using": by, "value": value})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: div.d_comment_text
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'MacBook-Pro.local', ip: '10.0.0.6', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.2', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAAoWnEkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJU0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3URU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90gHysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/XpELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQM6zAyIvdF4ixSbjadQhq87UXtRpTwwx+uBN3NjtyE9u4mIjc1WDVn+Ii4+I4xBhJwU04p6JEKH6nMxvfr0an02th/SKMQZyAfbE9Iy7Djzy83e5PTdXN9NTpSg2Gl1FrlErekg9nrH9KOu24F+6Ot+TTm5nQ0zi3ZqJRBGXdGk/zMkqQHHJa+Br7/1gvW1//L6cUaYEDJFzGYmweTS/L/LsjJVlV4OW1xW+/d6qcv4GrUR27WQKrFPy6oO6sS023Mdb/wfaaNjI5AG98KOiIu0Szo4wGi3yqTVE4mNC+TMLrPre1X6aPsVYLdl/ANQSwcIy87bUaYDAAC2DAAAUEsBAhQAFAAICAgAChacScvO21GmAwAAtgwAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA2wMAAAAA}, appBuildId=20161208153507, version=, platform=MAC, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=14171, browserVersion=50.1.0, platformVersion=16.3.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, takesElementScreenshot=true, platformName=darwin}]
Session ID: b7c9d43f-67b3-174e-ae6f-c140526aa6fe
*** Element info: {Using=css selector, value=div.d_comment_text}
Screenshot: available via screen
Stacktrace:
    at sun.reflect.GeneratedConstructorAccessor22.newInstance (None:-1)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:422)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException (W3CHttpResponseCodec.java:127)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:93)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:42)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute (HttpCommandExecutor.java:163)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute (DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:601)
    at org.openqa.selenium.remote.RemoteWebElement.execute (RemoteWebElement.java:274)
    at org.openqa.selenium.remote.RemoteWebElement.findElement (RemoteWebElement.java:177)
    at org.openqa.selenium.remote.RemoteWebElement.findElementByCssSelector (RemoteWebElement.java:242)
    at org.openqa.selenium.By$ByCssSelector.findElement (By.java:430)
    at org.openqa.selenium.remote.RemoteWebElement.findElement (RemoteWebElement.java:173)
    at sun.reflect.GeneratedMethodAccessor52.invoke (None:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:497)
    at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke (EventFiringWebDriver.java:331)
    at com.sun.proxy.$Proxy7.f [...]

2016-12-28 11:46 UTC, dkotegov commented
Принято

2016-12-28 11:46 UTC, closed without merging