Команда mini_bikini
dkotegov/selenium-homework pull request #8
Opened 2016-12-12 20:53 UTC by snach

Состав:
	Сначева Ксения
	Филатов Степан
	Лавриненко Адександр

Чеклист mini_bikini:

	1. Проверить настройки группы
		a. Переименовать группу
		b. Изменить описание группы
		с. Изменить город группы
	2. Проверить создание и удаление постов
		a. Пост с текстом
			1. Создать пост с текстом
			2. Удалить пост с текстом
		b. Пост с музыкой
			1. Создать пост с музыкой
			2. Удалить пост с музыкой
		с. Пост с выключенным режимом комментариев
			1. Создать пост с выключенным режимом комментариев
			2. Удалить пост с выключенным режимом комментариев
	3. Проверить навигацию по группам
		а. переход в группы
		b. Постраничная загрузка списка групп
		c. Возможность создания группы
		d. Поиск по группам
		e. Возможность перехода в группу из списка моих групп

2016-12-17 12:56 UTC, dkotegov commented
Нужно сделать на seismograph

2016-12-17 13:15 UTC, dkotegov requested changes

2016-12-17 13:15 UTC, dkotegov commented on tests/test_base.py
> +import time
Лишний импорт

2016-12-17 13:15 UTC, dkotegov commented on tests/test_creation_post.py
> +                 "/span[@class='posting-form_track_info ellip']"
Этот селектор будет работать не стабильно

2016-12-17 13:15 UTC, dkotegov commented on tests/test_creation_post.py
> +        last_post.delete()
Если ассерты выше упадут, эта строчка не выполнится

2016-12-17 13:15 UTC, dkotegov commented on tests/test_group_navigation.py
> +        except:
Плохо перехватывать всё

2016-12-17 13:15 UTC, dkotegov commented on tests/test_group_navigation.py
> +        while True:
Зачем?

2016-12-17 13:15 UTC, dkotegov commented on tests/test_group_navigation.py
> +            try:
Можно без try except и while true, пусть падает, если не получилось

2016-12-17 13:15 UTC, dkotegov commented on tests/test_group_navigation.py
> +        # print("create publci page tapped")
Не выглядит законченным

2016-12-17 13:15 UTC, dkotegov commented on tests/test_group_navigation.py
> +        # )
Почему закомменчено?

2016-12-18 18:46 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        # print("create publci page tapped")
Можно подробнее? Это открывающийся диалог, на нем кликается кнопка и происходят следующие действия

2016-12-18 18:47 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        # )
Я закоментил эту часть кода, потому что иногда страница не подгружается полностью, тест зависает и падает. Разумеется, мне бы хотелось удалить группу перед выходом, Но оно не всегда работает

2016-12-18 18:48 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        while True:
Исправлено

2016-12-18 18:48 UTC, LemonRuss commented on tests/test_group_navigation.py
> +            try:
Исправлено

2016-12-18 18:48 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        except:
Исправлено, перехыватываю только TimeOutExeption

2016-12-18 18:50 UTC, dkotegov commented on tests/test_group_navigation.py
> +        # )
Что значит "не подгружается полностью"?
Wait нужен для того, чтобы дожидаться, если что-то подтормаживает или пройти мгновенно, если нет

2016-12-18 18:50 UTC, dkotegov commented on tests/test_group_navigation.py
> +        # print("create publci page tapped")
Я про дебажные принты в коде

2016-12-18 18:51 UTC, snach commented on tests/test_creation_post.py
> +                 "/span[@class='posting-form_track_info ellip']"
исправила

2016-12-18 18:51 UTC, snach commented on tests/test_base.py
> +import time
исправила

2016-12-18 18:52 UTC, snach commented on tests/test_creation_post.py
> +        last_post.delete()
исправила, засунула в tear_down

2016-12-18 18:52 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        # print("create publci page tapped")
Убрал принты

2016-12-18 18:53 UTC, snach commented
Все переписано на сейсмограф

2016-12-18 18:53 UTC, dkotegov commented on tests/test_creation_post.py
> +            return False
`return self.driver.find_element_by_xpath(self.LAST_POST).text == text`

2016-12-18 18:55 UTC, LemonRuss commented on tests/test_creation_post.py
> +            return False
Аргумент

2016-12-18 18:56 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        # )
Проверил 10 раз - все работает. Раскоменчиваю обратно)

2016-12-18 18:59 UTC, dkotegov commented on tests/test_group_navigation.py
> +    #     self.assertion.equal(search_result, self.GROUP_NAME)
Пустая suite, забыли раскомментировать?

2016-12-18 19:00 UTC, LemonRuss commented on tests/test_group_navigation.py
> +    #     self.assertion.equal(search_result, self.GROUP_NAME)
Все вернул на место)

2016-12-18 19:00 UTC, dkotegov commented on tests/base_case.py
> +    PASSWORD = 'testQA1'
Ну блин

2016-12-18 19:01 UTC, dkotegov commented on tests/test_creation_post.py
> +        # print text
И тут

2016-12-18 19:02 UTC, dkotegov commented on tests/test_group_navigation.py
> +                lambda d: d.find_element_by_id("scrollToTop")
find_element и так скроллит до элемента, зачем этот костыль?

2016-12-18 19:03 UTC, dkotegov commented on tests/test_group_navigation.py
> +        self.assertion.equal(scrolled, True)
assert.true?

2016-12-18 19:03 UTC, LemonRuss commented on tests/test_group_navigation.py
> +                lambda d: d.find_element_by_id("scrollToTop")
Кнопка "вернуться в начало" появляется только после скролла. Поэтому сначала скролю, затем проверяю ее наличие

2016-12-18 19:03 UTC, dkotegov commented on tests/test_group_navigation.py
> +        self.groups_page.open()
Можно засунуть в setUp

2016-12-18 19:04 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        self.assertion.equal(scrolled, True)
У самого небольшие сомнения. В переменных scrolled - bool отскролилось или нет. Если не True - надо прервать

2016-12-18 19:06 UTC, snach commented on tests/test_creation_post.py
> +            return False
не согласна, имхо проверять в самом тесте наглядней, как реализовано это сейчас 
![image](https://cloud.githubusercontent.com/assets/17140006/21295815/37da00c2-c56e-11e6-97f2-32c29faaedfe.png)

2016-12-18 19:07 UTC, snach commented on tests/base_case.py
> +    PASSWORD = 'testQA1'
исправили

2016-12-18 19:07 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        self.assertion.equal(scrolled, True)
Как посоветуете?

2016-12-18 19:08 UTC, snach commented on tests/test_creation_post.py
> +        # print text
исправила

2016-12-18 19:08 UTC, LemonRuss commented on tests/base_case.py
> +    PASSWORD = 'testQA1'
Этого не было) Вам показалось

2016-12-18 19:11 UTC, dkotegov commented on tests/test_creation_post.py
> +            return False
Лучше сделать в самом тесте что-то вроде:
```
expected_text = "something"
actual_text = self.group_page.get_last_post_text()
self.assertion.equal(actual_text,expected_text)
```

2016-12-18 19:13 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        self.groups_page.open()
Засунул

2016-12-18 19:15 UTC, dkotegov commented on tests/test_group_navigation.py
> +        self.assertion.equal(scrolled, True)
Выпилить этот assert и try в scroll_to_bottom, оно упадет, если не отскроллится
В трейсе будет строка с scroll_to_bottom и TimeoutException в Wait, можно будет быстро понять в чем дело

2016-12-18 19:17 UTC, LemonRuss commented on tests/test_group_navigation.py
> +        self.assertion.equal(scrolled, True)
Выполнил

2016-12-18 19:17 UTC, snach commented on tests/test_creation_post.py
> +            return False
ненужное увеличение строк в каждом тексте, но если надо, я сделаю

2016-12-18 19:18 UTC, dkotegov commented
Не отлаживайтесь об преподавателя, спокойно исправьте замечания, найдите похожие ошибки, поревьюйте друг друга и пишите, когда будет готово :)

2016-12-18 19:23 UTC, dkotegov commented on tests/test_creation_post.py
> +            return False
Так меньше же, весь is_last_post_new_post можно будет выпилить :)

2016-12-18 19:25 UTC, dkotegov commented on tests/test_creation_post.py
> +        self.driver.find_element_by_xpath(self.LAST_POST).click()
Wait возвращает элемент в случае успеха, можно чему-нибудь присвоить и кликнуть уже его

2016-12-18 19:41 UTC, snach commented on tests/test_creation_post.py
> +            return False
с is_last_post_new_post была одна, а теперь две

last_post_text = last_post.get_last_post_text()
self.assertion.equal(self.text, last_post_text)

2016-12-18 19:41 UTC, snach commented on tests/test_creation_post.py
> +            return False
исправила

2016-12-18 19:43 UTC, snach commented on tests/test_creation_post.py
> +            return False
у трека(ниже), тоже исправила

2016-12-18 19:45 UTC, snach commented on tests/test_creation_post.py
> +        self.driver.find_element_by_xpath(self.LAST_POST).click()
тогда можно так написать???
WebDriverWait(self.driver, 30, 0.1).until(
+            lambda d: d.find_element_by_xpath(self.LAST_POST)
+        ).click()

2016-12-18 19:45 UTC, snach commented on tests/test_creation_post.py
> +        self.driver.find_element_by_xpath(self.LAST_POST).click()
WebDriverWait(self.driver, 30, 0.1).until(
            lambda d: d.find_element_by_xpath(self.LAST_POST_A)
       ).click()

2016-12-18 20:03 UTC, snach commented on tests/test_creation_post.py
> +        self.driver.find_element_by_xpath(self.LAST_POST).click()
так можно, я исправила

2016-12-18 20:04 UTC, snach commented
мы исправили :)

2016-12-18 23:09 UTC, dkotegov commented
Тесты падают и зависают:
```
MacBook-Pro:selenium-homework (master) Dmitry$ python run_tests.py
Seismograph is measuring:

.E.E^C

Seismograph is reporting about reasons:

========================================================================================================================
<tests.test_creation_post:CreationPostTest method_name=test_post_without_comments stopped_on=test_post_without_comments>
========================================================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/test_creation_post.py", line 201, in test_post_without_comments
    self.assertion.true(last_post.is_last_post_without_comments())
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/test_creation_post.py", line 109, in is_last_post_without_comments
    lambda d: d.find_element_by_xpath(self.COMMENT_CLOSED)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:
Screenshot: available via screen
Stacktrace:
    at sun.reflect.GeneratedConstructorAccessor14.newInstance (None:-1)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:422)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException (W3CHttpResponseCodec.java:127)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:93)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:42)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute (HttpCommandExecutor.java:163)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute (DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:601)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement (RemoteWebDriver.java:368)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath (RemoteWebDriver.java:473)
    at org.openqa.selenium.By$ByXPath.findElement (By.java:361)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement (RemoteWebDriver.java:360)
    at sun.reflect.GeneratedMethodAccessor14.invoke (None:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:497)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke (EventFiringWebDriver.java:103)
    at com.sun.proxy.$Proxy6.findElement (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver.findElement (EventFiringWebDriver.java:187)
    at org.openqa.selenium.remote.server.handler.FindElement.call (FindElement.java:48)
    at org.openqa.selenium.remote.server.handler.FindElement.call (FindElement.java:33)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)

=======================================================================================================
<tests.test_group_settings:GroupsSettingsTest method_name=test_change_city stopped_on=test_change_city>
=======================================================================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/case.py", line 836, in __run__
    test_method()
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/test_group_settings.py", line 128, in test_change_city
    self.main_settings.change_city(last_city)
  File "/Users/Dmitry/TPHomeWork/stud/selenium-homework/tests/test_group_settings.py", line 69, in change_city
    lambda d: d.find_element_by_xpath(self.Moscow)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:
Screenshot: available via screen
Stacktrace:
    at sun.reflect.GeneratedConstructorAccessor14.newInstance (None:-1)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:422)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException (W3CHttpResponseCodec.java:127)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:93)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:42)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute (HttpCommandExecutor.java:163)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute (DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:601)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement (RemoteWebDriver.java:368)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath (RemoteWebDriver.java:473)
    at org.openqa.selenium.By$ByXPath.findElement (By.java:361)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement (RemoteWebDriver.java:360)
    at sun.reflect.GeneratedMethodAccessor14.invoke (None:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:497)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke (EventFiringWebDriver.java:103)
    at com.sun.proxy.$Proxy6.findElement (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver.findElement (EventFiringWebDriver.java:187)
    at org.openqa.selenium.remote.server.handler.FindElement.call (FindElement.java:48)
    at org.openqa.selenium.remote.server.handler.FindElement.call (FindElement.java:33)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)

-----------------------------------------------------------------
tests=4 failures=0 errors=2 skipped=0 successes=2 runtime=111.581
Traceback (most recent call last):
  File "run_tests.py", line 16, in <module>
    seismograph.main(config_path='config.py', suites=suites)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/program.py", line 517, in main
    Program(*args, **kwargs),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/runnable.py", line 13, in run
    return runnable.__run__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/program.py", line 205, in __run__
    group(self.__result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/runnable.py", line 106, in __call__
    return self.__run__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/seismograph/groups/default.py", line 16, in __run__
    suite(result)
  File "/Library/Frameworks/Python.framework/ [...]

2016-12-19 15:39 UTC, snach commented
МЫ ИСПРАВИЛИ :)

2016-12-19 15:43 UTC, LemonRuss commented
P.S.
Прощу заметить, что тесты упали из за обновления, которое было судя по всему в ночь с воскресенья на понедельник. Изменились некоторые элементы, на которые мы опирались

2016-12-19 20:23 UTC, dkotegov commented on tests/test_creation_post.py
> +        comment.click()
Похоже на костыль, зачем 3 клика? ;)

2016-12-19 20:23 UTC, dkotegov commented
Принято

2016-12-19 20:23 UTC, closed without merging